### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by ilovebamboo** [iMuFeng/iUnlocker#1]
![Uploading 48471BFE-D445-466A-9297-65E2894F38DE.png…]()

**Comment by ilovebamboo** [comment]
编译错误了

**Comment by iMuFeng** [comment]
可以帖一下具体的错误信息

**Comment by iMuFeng** [comment]
有可能你修改一下 Bundle Identifier 再试试

**Comment by ilovebamboo** [comment]
不行啊 又不能发图片。能不能给我一个编译好的 谢谢。邮箱xuezia@qq.com

**Comment by iMuFeng** [comment]
我编译好的，你的手机也是无法使用的

**Comment by ilovebamboo** [comment]
越狱的也不行吗？

**Comment by ilovebamboo** [comment]
http://www.cocoachina.com/ios/20160601/16557.html 是不是需要POD支持

**Comment by ilovebamboo** [comment]
https://github.com/kattrali/cocoapods-xcode-plugin

**Comment by iMuFeng** [comment]
cocoapods 依赖已经在上传的代码中了
